smoothies = {
    "Banana, Mango and Spinach": {"Type": "E", "Cal(kcal)": 492,
                                  "Carbs(g)": 47, "Ingred": "FV"},
    "Spinach, Mango and Pineapple": {"Type": "E", "Cal(kcal)": 163,
                                     "Carbs(g)": 36, "Ingred": "FV"},
    "Cherry and Orange": {"Type": "E", "Cal(kcal)": 296,
                          "Carbs(g)": 36, "Ingred": "F"},
    "Rasberry and Apple": {"Type": "E", "Cal(kcal)": 106,
                           "Carbs(g)": 14, "Ingred": "F"},
    "Pineapple, Celery and Spinach": {"Type": "E", "Cal(kcal)": 90,
                                      "Carbs(g)": 19, "Ingred": "FV"},
    "Strawberry, Spinach and Orange": {"Type": "E", "Cal(kcal)": 226,
                                       "Carbs(g)": 16, "Ingred": "FV"},
    "Rasberry and Avacado": {"Type": "E", "Cal(kcal)": 231,
                             "Carbs(g)": 13, "Ingred": "F"},
    "Passion fruit and Banana": {"Type": "E", "Cal(kcal)": 189,
                                 "Carbs(g)": 37, "Ingred": "F"},
    "Peach and Yoghurt": {"Type": "I", "Cal(kcal)": 309,
                          "Carbs(g)": 7, "Ingred": "F"},
    "Bluberry, Avacado and Cocounut": {"Type": "I", "Cal(kcal)": 289,
                                       "Carbs(g)": 47, "Ingred": "F"},
    "Pineapple and Turmeric": {"Type": "I", "Cal(kcal)": 180,
                               "Carbs(g)": 41, "Ingred": "F"},
    "Avacado, Banana and Kale": {"Type": "I", "Cal(kcal)": 252,
                                 "Carbs(g)": 17, "Ingred": "FV"},
    "Apple, Carrot and Beetroot": {"Type": "I", "Cal(kcal)": 134,
                                   "Carbs(g)": 33, "Ingred": "FV"},
    "Kale and Spinach": {"Type": "I", "Cal(kcal)": 419,
                         "Carbs(g)": 51, "Ingred": "FV"},
    "Apricot and Strawberry": {"Type": "I", "Cal(kcal)": 116,
                               "Carbs(g)": 23, "Ingred": "F"},
    "Spinach, Avacado and Cucumber": {"Type": "I", "Cal(kcal)": 126,
                                      "Carbs(g)": 10, "Ingred": "FV"}
}


smoothie_ingrediants = {
    "pineapple, celery and spinach": ["1/2 cup low fat vanilla yoghurt", "3 slices pineapple", "1 stalk celery", "2 cups fresh spinach", "2 cups ice"],
    "Banana and Avacado": ["1 cup almond milk", "2 medium bananas", "1/2 avacado", "2 dates", "1 cup ice"],
    "Banana, Blueberry and Orange": ["4 medium oranges", "4 small bananas frozen", "1 1/2 cups frozen blueberries", "3 cups water"],
    "Cherry and orange": ["2 cups frozen pitted cherries", "1/2 cup ground almonds", "2 tbsp flaxseed meal", "1/2 tsp pure almond extract"],
    "rasberry and apple": ["2 apples", "150g frozen rasberries", "150ml natural yoghurt", "2 tbsp porridge oats", "1/2 lemon", "100ml milk"],
    "Strawberry, Spinach and Orange": ["160g ripe strawberries", "160g baby spinach", "1 avacado", "150ml bio yoghurt", "2 small oranges", "1/2 tsp orange zest"],
    "Rasberry and Avacado": ["1 avacado", "3/4 cup rasberries", "1 tbsp lemon juice", "1 1/2 cup unsweetened coconut milk", "1 cup vanilla protein powder"],
    "Passion fruit and Banana": ["3 passion fruits", "1 banana", "1 small mango", "300ml orange juice"],
    "Mango and banana": ["2 bananas", "3 cups mango chunks", "1 1/4 cup almond milk"],
    "Peach and yoghurt": ["3 cups sliced peaches", "1 cup greek yoghurt", "1 cup almond milk", "2 tbsp honey"],
    "Avacado, banana and kale": ["1 avacado", "1 banana", "1 cup baby kale", "1 1/2 cup almond milk", "2 tbsp vanilla protein powder"],
    "Bluberry, avacado and cocounut": ["2 cups frozen blueberries", "1 frozen banana", "1/2 cup greek yoghurt", "1 tbsp flaxseeds", "2 cups coconut water"],
    "Pineapple and turmeric": ["2 cups frozen pineapple chunks", "1 banana", "1 cup dairy free milk", "1 tbsp fresh turmeric", "1 tsp ginger"],
    "Apple, Carrot and Beetroot": ["1 red beetroot", "3 carrots", "1 orange", "1 2inch piece ginger", "1 cup cold water"],
    "Kale and Spinach": ["1 cup baby kale", "1 cup spinach", "5 dates", "1 kiwi", "2 tbsp almond butter", "1 cup unsweetened almond milk"],
    "Apricot and Strawberry": ["1 cup frozen strawberries", "2 frozen apricots", "1 cup unsweetened almond milk"]
}